import { HistoryEntry, TotalCoverage } from './types.js';

export class MarkdownGenerator {
  private history: HistoryEntry[];
  private current: TotalCoverage;

  constructor(history: HistoryEntry[], current: TotalCoverage) {
    this.history = history;
    this.current = current;
  }

  generate(injectMode = false): string {
    const c = this.current.total;
    const historyLines = this.history.map((h) => h.metrics.lines.pct);
    const dateLabels = this.history.map((h) => new Date(h.timestamp).toISOString().split('T')[0]);

    // Mermaid XY Chart (Beta) or Line Chart
    const mermaidChart = `
\`\`\`mermaid
---
title: Coverage Trend (Lines %)
---
xychart-beta
    title "Coverage History"
    x-axis [${dateLabels.join(', ')}]
    y-axis "Percentage" 0 --> 100
    line [${historyLines.join(', ')}]
\`\`\`
    `;

    const report = `
# Cocov Intelligence Report

## 📊 Coverage Summary
| Metric | % | Status |
| :--- | :--- | :--- |
| **Lines** | ${c.lines.pct}% | ${this.getStatusIcon(c.lines.pct)} |
| **Statements** | ${c.statements.pct}% | ${this.getStatusIcon(c.statements.pct)} |
| **Functions** | ${c.functions.pct}% | ${this.getStatusIcon(c.functions.pct)} |
| **Branches** | ${c.branches.pct}% | ${this.getStatusIcon(c.branches.pct)} |

## 📈 Trend Analysis
${this.history.length > 0 ? mermaidChart : '_No history available yet._'}

> **Note**: This report is auto-generated by Cocov.
    `.trim();

    if (injectMode) {
      return `<!-- cocov-start -->\n${report}\n<!-- cocov-end -->`;
    }
    return report;
  }

  private getStatusIcon(pct: number): string {
    if (pct >= 90) return '✅';
    if (pct >= 80) return '⚠️';
    return '🚨';
  }
}
