
import fs from 'fs';
import path from 'path';

const cwd = process.cwd();
const finalPath = path.join(cwd, 'coverage/coverage-final.json');

async function run() {
    if (!fs.existsSync(finalPath)) {
        console.log('No coverage data found.');
        return;
    }

    const content = fs.readFileSync(finalPath, 'utf-8');
    const data = JSON.parse(content);
    let md = '# 📝 Coverage TODO List\n\nGenerated by Cocov. Use this list to reach 100% coverage.\n\n';
    let hasGaps = false;

    // Iterate files
    for (const [filePath, cov] of Object.entries(data)) {
        const relPath = path.relative(cwd, filePath);
        const { lines, statements, functions, branches } = cov;
        
        // Simple metric check: Just check overall stats or dig into 's', 'f', 'b' maps
        // For 'coverage-final.json' (Istanbul), we look at 's', 'f', 'b' maps
        
        let missing = [];

        // Statements
        if (cov.s) {
            for (const [id, count] of Object.entries(cov.s)) {
                if (count === 0) {
                    const range = cov.statementMap[id];
                    if (range) missing.push(`Statement L${range.start.line}`);
                }
            }
        }
        
        // Functions
        if (cov.f) {
            for (const [id, count] of Object.entries(cov.f)) {
                 if (count === 0) {
                    const decl = cov.fnMap[id];
                    if (decl) missing.push(`Function ${decl.name || 'anon'} L${decl.loc.start.line}`);
                }
            }
        }

        // Branches
        if (cov.b) {
            for (const [id, counts] of Object.entries(cov.b)) {
                const cArr = counts;
                cArr.forEach((c, i) => {
                    if (c === 0) {
                        const range = cov.branchMap[id];
                        if (range) missing.push(`Branch L${range.loc.start.line} #${i}`);
                    }
                });
            }
            
        }

        if (missing.length > 0) {
            hasGaps = true;
             md += `## 🔴 ${relPath}\n`;
             md += `- [ ] ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? '...' : ''}\n`;
        }
    }

    if (!hasGaps) {
        md += '## ✅ All clear! 100% Coverage achieved.\n';
        md += 'Go Ranger! Mission Accomplished.';
    }

    fs.writeFileSync(path.join(cwd, 'TODO_TESTS.md'), md);
    console.log('Generated TODO_TESTS.md');
}

run().catch(console.error);
